config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/search', to: 'static_pages#search'
  
  devise_for :user, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users, only: [] do
    resource :profile, only: [:create, :update, :show]
  end
  resources :notifications, only: [:index]
  resources :friendships, except: [:new]
  resources :posts, only: [:index, :create] do 
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  def notify
    if status == "friend"
      message = "accepted your friend request!"
      sender.notifications.create(family: "friend_request_accepted", message: message, what: id, who: receiver_id)
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  MSG = { "friend_request_accepted" => "accepted your friend request!",
    "like" => "likes your post!", "comment" => "commented your post!"} 

  def display_msg
    MSG[self.family]
  end
  
  def who_full_name
    User.find(self.who).name
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  has_one_attached :photo

  validates :body, presence: true

  def optimized_photo(x,y)
    photo.variant(resize_to_limit: [x,y])
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  def optimized_photo(x,y)
    photo.variant(resize_to_limit: [x,y])
  end
end

app/models/user.rb
require 'open-uri' 

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  validates :name, :birthdate, :gender, presence: true

  has_many :notifications, dependent: :destroy
  
  has_many :sent_friendships, class_name: "Friendship", dependent: :destroy, inverse_of: :sender, foreign_key: "sender_id"
  has_many :sent_friends, through: :sent_friendships, source: :receiver
  has_many :received_friendships, class_name: "Friendship", dependent: :destroy, inverse_of: :receiver, foreign_key: "receiver_id"
  has_many :received_friends, through: :received_friendships, source: :sender

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one :profile

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(name: data['name'],
            email: data['email'],
            gender: "Male",
            birthdate: DateTime.now,
            password: Devise.friendly_token[0,20]
        )
      user.create_profile
      user.profile.photo.attach(io: open(data['image']), filename:"photo.jpg")
    end
    user
  end

  def friends_ids
    (sent_friendships.where(status: "friend").pluck(:receiver_id) + received_friendships.where(status: "friend").pluck(:sender_id)).uniq
  end  
  
  def friend_requester_ids
    received_friendships.where(status: "friend_request").pluck(:sender_id)
  end

  def friends
    (sent_friends + received_friends).uniq.filter { |u| !friend_requester_ids.include?(u.id) }
  end

  def new_friend_request?
    received_friendships.where(status: "friend_request").count > 0
  end

  def new_friend_request_count
    received_friendships.where(status: "friend_request").count
  end

  def new_notifications?
    notifications.where(viewed: false).count > 0
  end

  def new_notifications_count
    notifications.where(viewed: false).count
  end

  def likes_this?(post)
    likes.where(post_id: post.id).any?
  end

  def this_like_id(post)
    likes.where(post_id: post.id).first.id
  end

  def age
    dob = birthdate
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birthdate, :gender])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    comment = current_user.comments.build(comment_params)
    if comment.valid?
      comment.save
      Post.find(params[:comment][:post_id]).user.notifications.create(family: "comment", what: params[:comment][:post_id], who: current_user.id)
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
    @new_friend_requests = current_user.received_friendships.where(status: "friend_request")
  end

  def create
    receiver = User.find(params[:receiver_id])
    f = Friendship.create(sender: current_user ,receiver: receiver)
    flash[:notice] = "Friend Request sent to #{receiver.name}!" 
    redirect_back(fallback_location: root_path)
  end

  def update
    f = Friendship.find(params[:id])
    f.update(status: "friend")
    f.notify
    flash[:notice] = "#{f.sender.name} is now your friend!" 
    redirect_back(fallback_location: root_path)
  end

  def destroy
    Friendship.find(params[:id]).delete
    flash[:notice] = "Friend request deleted!" 
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    current_user.likes.create(post_id: params[:post_id])
    Post.find(params[:post_id]).user.notifications.create(family: "like", what: params[:post_id], who: current_user.id)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    Like.find(params[:id]).delete
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.where(user_id: current_user.friends_ids<<current_user.id).order(created_at: :desc)

    @new_post = current_user.posts.build
    @new_commment = current_user.comments.build
  end

  def create
    current_user.posts.create(post_params)

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:body, :photo)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def create
    current_user.create_profile(profile_params)
    redirect_back(fallback_location: user_profile_path(current_user.id))
  end

  def update
    current_user.profile.update(profile_params)
    redirect_back(fallback_location: user_profile_path(current_user.id))
  end

  def show
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @posts = @user.posts
  end

  private

  def profile_params
    params.require(:profile).permit(:photo)
  end

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def search
    @users = User.where("id != ? AND lower(name) like ?", current_user.id, "%#{params[:q].downcase}%")
    @sent_requests_users_id = current_user.sent_friendships.map { |r| r.receiver.id }
    @friends_ids = current_user.friends_ids
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_form.html.erb
<%= form_with model: @new_comment, scope: :comment, url: post_comments_path(p) do |f| %>
  <%= f.hidden_field :post_id, value: p.id %>
  <%= f.text_field :body, class: "input" %>
  <%= f.submit 'Comment', class:"btn-small" %>
<% end %>

app/views/comments/_list_comments.html.erb
<div>
  <% if comments.any? %>
    <small><%= pluralize(comments.count, "comment") %>:</small>
    <% comments.each do |comment| %>
      <p class="ml-6 text-sm">
        <strong><%= link_to comment.user.name, user_profile_path(comment.user.id) %>:</strong> <%= comment.body %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/friendships/index.html.erb
<div class="central_panel w-4/5 sm:w-3/5 md:w-1/2 lg:w-2/5">
  <h2 class="text-lg pb-2">
    <%= pluralize(current_user.new_friend_request_count, "friend request") %> :
  </h2>
  <% @new_friend_requests.each do |f| %>
  <% if User.exists?(f.sender_id) %>
    <p>
      <%= f.sender.name %> sent you a friend request! <br/>
      <small><%= time_ago_in_words(f.created_at) + " ago." %></small> 
    </p>
    <div class="pt-2">
      <%= link_to 'Accept Friend Request', friendship_path(f), method: :patch, class:"inline-block btn-small" %>
      <%= link_to 'Dismiss Friend Request', friendship_path(f), method: :delete, class:"inline-block btn-small-alert " %>
    </div>
  <% end %>
  <% end %>
</div>

app/views/posts/_comment_form.html.erb
<%= form_with model: @new_comment, scope: :comment, url: post_comments_path(p) do |f| %>
  <%= f.hidden_field :post_id, value: p.id %>
  <%= f.text_field :body, class: "input" %>
  <%= f.submit 'Comment', class:"btn-small" %>
<% end %>

app/views/posts/_post.html.erb
<div>
  <strong><%= link_to p.user.name, user_profile_path(p.user.id) %>:</strong> <%= p.body %><br>
  <small><%= time_ago_in_words(p.created_at) + " ago." %></small><br>
  <% if p.photo.attached? %>
    <div class="mb-2">
        <%= image_tag p.optimized_photo(200,200) %>
    </div>
  <% end %>
  <% if current_user.likes_this?(p) %>
    <%= link_to post_like_path(p, current_user.this_like_id(p)), method: :delete do %>
      <%= image_tag 'icons/you_like.png', alt:"Friendss", class:"inline-block w-6 mb-1" %>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(p), method: :post do %>
      <%= image_tag 'icons/like.png', alt:"Friends", class:"inline-block w-6 mb-1 opacity-25" %>
    <%  end %>
  <% end %>
  <% if p.likes.any? %>
    <small><%= pluralize(p.likes.count, "like") %>:
      <%= p.likes.map { |l| l.user.name }.join(", ") %>
    </small>
  <% end %>
</div>

app/views/posts/_post_form.html.erb
<%= form_for @new_post do |f| %>
  <%= f.text_area :body, autofocus: true, class: "input h-20 autofocus" %>
  <%= f.submit "Post", class: "btn-main" %>
  <%= f.file_field :photo, class:"" %>
<% end %>

app/views/posts/index.html.erb
<div class="central_panel w-4/5 sm:w-3/5 md:w-1/2 lg:w-2/5">
  <h2 class="text-xl mb-2">What's on your mind?</h2>
  <%= render 'post_form' %>
  <% @posts.each do |p| %>
    <% if User.exists?(p.user_id) %>
      <div class="p-4">
        <%= render 'post', p: p %>
        <%= render 'comments/list_comments', comments: p.comments  %>
        <div class="mt-1">
          <%= render 'comments/form', new_comment: @new_comment, p: p %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/profiles/_profile_form.html.erb
<%= form_with model: profile, url: user_profile_path(current_user.id) do |f| %>
  <%= f.file_field :photo, class:"mb-2" %><br>
  <%= f.submit 'Add photo', class:"btn-small" %>
<% end %>

app/views/profiles/show.html.erb
<div class="p-6 mx-auto sm:w-1/5 sm:float-left md:w-1/4 lg:w-2/5">

  <h2 class="text-xl mb-2"><%= @user.name %></h2>

  <div class="mb-4">
    <h2 class="text-xl mb-2">Profile picture:</h2>
    <% if @profile.photo.attached? %>
      <div class="mb-2">
        <%= image_tag @profile.optimized_photo(200,200) %>
      </div>
    <% end %>
    <% if @user == current_user %>
      <%= render 'profile_form', profile: @profile %>
    <% end %>
  </div>

  <h2 class="text-xl mb-2">Profile info:</h2>
  <p class="mb-4">
    Name: <%= @user.name %><br>
    Email: <%= @user.email %><br>
    Age: <%= pluralize(@user.age, "year") %> old<br>
  </p>
  <h2 class="text-xl mb-2">Activity:</h2>
  <p>
    <%= pluralize(@user.posts.count, "Post") %><br>
    <%= pluralize(@user.likes.count, "Like") %><br>
    <%= pluralize(@user.comments.count, "Comment") %>
  </p>
</div>

<div class="central_panel w-4/5 sm:w-3/5 md:w-1/2 lg:w-2/5">
  <h2 class="text-xl mb-2">Posts:</h2>
  <% @posts.each do |p| %>
    <div class="p-4">
      <%= render '/posts/post', p: p %>
      <%= render 'comments/list_comments', comments: p.comments  %>
    </div>
  <% end %>
</div>