config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/search', to: 'static_pages#search'
  
  devise_for :user, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users, only: [] do
    resource :profile, only: [:create, :update, :show]
  end
  resources :notifications, only: [:index]
  resources :friendships, except: [:new]
  resources :posts, only: [:index, :create] do 
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  def notify
    if status == "friend"
      message = "accepted your friend request!"
      sender.notifications.create(family: "friend_request_accepted", message: message, what: id, who: receiver_id)
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  MSG = { "friend_request_accepted" => "accepted your friend request!",
    "like" => "likes your post!", "comment" => "commented your post!"} 

  def display_msg
    MSG[self.family]
  end
  
  def who_full_name
    User.find(self.who).name
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  has_one_attached :photo

  validates :body, presence: true

  def optimized_photo(x,y)
    photo.variant(resize_to_limit: [x,y])
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  def optimized_photo(x,y)
    photo.variant(resize_to_limit: [x,y])
  end
end

app/models/user.rb
require 'open-uri' 

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  validates :name, :birthdate, :gender, presence: true

  has_many :notifications, dependent: :destroy
  
  has_many :sent_friendships, class_name: "Friendship", dependent: :destroy, inverse_of: :sender, foreign_key: "sender_id"
  has_many :sent_friends, through: :sent_friendships, source: :receiver
  has_many :received_friendships, class_name: "Friendship", dependent: :destroy, inverse_of: :receiver, foreign_key: "receiver_id"
  has_many :received_friends, through: :received_friendships, source: :sender

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one :profile

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(name: data['name'],
            email: data['email'],
            gender: "Male",
            birthdate: DateTime.now,
            password: Devise.friendly_token[0,20]
        )
      user.create_profile
      user.profile.photo.attach(io: open(data['image']), filename:"photo.jpg")
    end
    user
  end

  def friends_ids
    (sent_friendships.where(status: "friend").pluck(:receiver_id) + received_friendships.where(status: "friend").pluck(:sender_id)).uniq
  end  
  
  def friend_requester_ids
    received_friendships.where(status: "friend_request").pluck(:sender_id)
  end

  def friends
    (sent_friends + received_friends).uniq.filter { |u| !friend_requester_ids.include?(u.id) }
  end

  def new_friend_request?
    received_friendships.where(status: "friend_request").count > 0
  end

  def new_friend_request_count
    received_friendships.where(status: "friend_request").count
  end

  def new_notifications?
    notifications.where(viewed: false).count > 0
  end

  def new_notifications_count
    notifications.where(viewed: false).count
  end

  def likes_this?(post)
    likes.where(post_id: post.id).any?
  end

  def this_like_id(post)
    likes.where(post_id: post.id).first.id
  end

  def age
    dob = birthdate
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    comment = current_user.comments.build(comment_params)
    if comment.valid?
      comment.save
      Post.find(params[:comment][:post_id]).user.notifications.create(family: "comment", what: params[:comment][:post_id], who: current_user.id)
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    current_user.likes.create(post_id: params[:post_id])
    Post.find(params[:post_id]).user.notifications.create(family: "like", what: params[:post_id], who: current_user.id)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    Like.find(params[:id]).delete
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.where(user_id: current_user.friends_ids<<current_user.id).order(created_at: :desc)

    @new_post = current_user.posts.build
    @new_commment = current_user.comments.build
  end

  def create
    current_user.posts.create(post_params)

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:body, :photo)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def create
    current_user.create_profile(profile_params)
    redirect_back(fallback_location: user_profile_path(current_user.id))
  end

  def update
    current_user.profile.update(profile_params)
    redirect_back(fallback_location: user_profile_path(current_user.id))
  end

  def show
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @posts = @user.posts
  end

  private

  def profile_params
    params.require(:profile).permit(:photo)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_nav.html.erb
<nav class="bg-blue-500 py-4 px-4">
  <%= link_to 'Facebook', root_path, class:"inline-block text-2xl text-white font-bold" %>
  <% if user_signed_in? %>
    <%= link_to notifications_path, class: "inline-block ml-6" do %>
      <div class="relative align-middle">
        <% if current_user.new_notifications? %>
          <%= image_tag 'icons/notification_bell.png', alt:"Notifs", class:"inline-block mb-1 w-6" %>
          <div class="absolute w-6 top-1 text-white text-xs text-center font-light "><%= current_user.new_notifications_count %></div>
        <% else %>
          <%= image_tag 'icons/notifications.png', alt:"Notifs", class:"inline-block mb-1 w-6 opacity-25" %>
        <% end %>
      </div>
    <% end %>
    <%= link_to friendships_path, class: "inline-block ml-6" do %>
      <% if current_user.new_friend_request? %>
        <%= image_tag 'icons/new_friend.png', alt:"Friendss", class:"inline-block mb-1 w-6" %>
        <div class="absolute w-6 top-1 text-white text-xs text-center font-light "><%= current_user.new_friend_request_count %></div>
      <% else %>
        <%= image_tag 'icons/friend.png', alt:"Friends", class:"inline-block mb-1 w-6 opacity-25" %>
      <% end %>
    <% end %>
    <div class="inline-block ml-6">
      <%= form_with(url: "/search", method: :get, local: true ) do |f| %>
        <%= f.text_field :q, class: "px-2 py-1 inline-block" %>
        <%= f.submit "Find friend", class:"btn-small ml-2" %>
      <% end %>
    </div>

    <div class="float-right inline-block">
      <div class="relative">
        <%= link_to user_profile_path(current_user.id) do %>
        <div class="h-12">
          <% if current_user.profile && current_user.profile.photo.attached? %>
            <div class="inline-block align-middle mr-2 border-2 rounded-full overflow-hidden">
              <%= image_tag current_user.profile.optimized_photo(35,35) %>
            </div>
          <% end %>
          <span class="align-middle pr-8 text-white"><%= current_user.name %></span>
        </div>
        <% end %>
        <div class="absolute right-0 w-32 bg-white py-2 rounded shadow-lg">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "block py-2 pl-6 hover:bg-blue-500 hover:text-white" %>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "block py-2 pl-6 hover:bg-blue-500 hover:text-white" %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="float-right inline-block">
      <%= link_to 'Log in', new_user_session_path, class: "btn-small inline-block" %>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/nav' %>

    <% if notice || alert %>
      <p class="notice px-10 py-4 text-gray-800"><%= notice %></p>
      <p class="alert px-10 text-gray-800"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>